name: CI/CD pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  # Name of the job/test
  api_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Install Newman
        run: npm install -g newman
      - name: Install dotnet project dependencies
        run: cd server/server && dotnet restore
      - name: Build
        run: cd server/server && dotnet build
      - name: Start Server
        run: cd server/server && nohup dotnet run &
      - name: Run API-Tests
        run: cd server/server && newman run ./AlcoRel.postman_collection.json -e ./AlcoRel.postman_environment.json

  gui_tests:
    runs-on: ubuntu-latest
    needs: api_tests
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Install dotnet project dependencies
        run: dotnet restore
      - name: Build/Restore Playwright Project
        run: cd alcorel-gui.Tests && dotnet build
      - name: Ensure browsers are installed
        run: cd alcorel-gui.Tests && pwsh bin/Debug/net8.0/playwright.ps1 install --with-deps
      - name: Start server
        run: cd server/server && nohup dotnet run &
      - name: Run GUI-tests
        run: cd server/alcorel-gui.Tests && dotnet test

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: [api_tests, gui_tests] # Kör endast om alla tidigare tester är OK
    steps:
      - name: Deploy App
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            source /root/.nvm/nvm.sh
            nvm use v20.12.2
            cd /srv/www/shoptester
            git pull
            cd client
            npm ci
            npm run build
            cd ../server
            dotnet restore
            pm2 stop shoptester
            pm2 delete shoptester
            pm2 start "dotnet run" --name shoptester
