name: CI/CD pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  # Name of the job/test
  api_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Install Newman
        run: npm install -g newman
      - name: Install dotnet project dependencies
        run: cd server/server && dotnet restore
      - name: Build
        run: cd server/server && dotnet build
      - name: Start Server
        run: cd server/server && nohup dotnet run &
      - name: Run API-Tests
        run: cd server/server && newman run ./AlcoRel.postman_collection.json -e ./AlcoRel.postman_environment.json

  gui_tests:
    runs-on: ubuntu-latest
    needs: api_tests
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Install dependencies
        run: sudo apt-get install -y libnss3 libatk1.0-0 libatk-bridge2.0-0 libx11-xcb1 libxcomposite1 libxdamage1 libxrandr2 libgbm1 libasound2 libxshmfence1 libxfixes3 libxrender1 libxext6 libx11-6 libc6
      - name: Install dotnet project dependencies
        run: cd server/server && dotnet restore
      - name: Build/Restore Playwright Project
        run: cd server/alcorel-gui.Tests && dotnet build
      - name: Ensure browsers are installed
        run: cd server/alcorel-gui.Tests && pwsh bin/Debug/net8.0/playwright.ps1 install --with-deps
      - name: Start server
        run: cd server/server && nohup dotnet run &
      - name: Run GUI-tests
        run: cd server/alcorel-gui.Tests && dotnet test

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: [api_tests, gui_tests] # Kör endast om alla tidigare tester är OK OK
    steps:
      - name: Deploy App
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /srv/www/halmstad/edvin
            git clone https://github.com/edvinrunhellen/Alcorel-GUI-Testing.git
